// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(12
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc019RW4jOVhuCSmmc_god5bpTo06c-bQ',
    appId: '1:235547997088:web:f17969139e0fe0d2b12ac5',
    messagingSenderId: '235547997088',
    projectId: 'news-3c67d',
    authDomain: 'news-3c67d.firebaseapp.com',
    storageBucket: 'news-3c67d.firebasestorage.app',
    measurementId: 'G-KQSVNF0TH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfJKU353V-De4DXak1GXE2veSIzNaiVuo',
    appId: '1:235547997088:android:b413eecc6f1b8e27b12ac5',
    messagingSenderId: '235547997088',
    projectId: 'news-3c67d',
    storageBucket: 'news-3c67d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNrKviqkGavRnVbDtQ_cfYWQbi5rlXcw8',
    appId: '1:235547997088:ios:f93e3f7180cc25d7b12ac5',
    messagingSenderId: '235547997088',
    projectId: 'news-3c67d',
    storageBucket: 'news-3c67d.firebasestorage.app',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNrKviqkGavRnVbDtQ_cfYWQbi5rlXcw8',
    appId: '1:235547997088:ios:f93e3f7180cc25d7b12ac5',
    messagingSenderId: '235547997088',
    projectId: 'news-3c67d',
    storageBucket: 'news-3c67d.firebasestorage.app',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc019RW4jOVhuCSmmc_god5bpTo06c-bQ',
    appId: '1:235547997088:web:96107a9fb8902f48b12ac5',
    messagingSenderId: '235547997088',
    projectId: 'news-3c67d',
    authDomain: 'news-3c67d.firebaseapp.com',
    storageBucket: 'news-3c67d.firebasestorage.app',
    measurementId: 'G-6WCV5EXR9B',
  );
}
